import './globals.css'
import { dmSans } from '@/app/ui/fonts'
import { AuthProvider } from './context/AuthContext'
import { Toaster } from 'react-hot-toast'

export const metadata = {
  title: 'Heirs Technologies E-invoicing',
  description: 'Generated by Heirs Technologies',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dmSans.className} antialiased`}>
        <AuthProvider>
          {children}
          <Toaster position="top-right" reverseOrder={false} />
        </AuthProvider>
      </body>
    </html>
  )
}
