import './globals.css'
import { dmSans } from '@/app/ui/fonts'

export const metadata = {
  title: 'Heirs Technologies E-invoicing',
  description: 'Generated by Heirs Technologies',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dmSans.className} antialiased`}>
        {children}
      </body>
    </html>
  )
}
